workflows:
  android_release:
    name: Android Release APK
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest

    scripts:
      - name: 🔹 Подготовка проекта
        script: |
          set -euo pipefail
          echo "🧹 Очистка и установка зависимостей..."
          flutter clean
          flutter pub get

      - name: 🔹 Сборка релизного APK
        script: |
          set -euo pipefail
          echo "🏗️ Собираем релиз (flutter build apk)..."
          BN=$(date +%s)

          set +e
          flutter build apk --release \
            --build-number="$BN" \
            --build-name="1.0.$BN" \
            --no-shrink -v
          FLUTTER_RC=$?
          set -e

          if [ $FLUTTER_RC -ne 0 ]; then
            echo "⚠️ Flutter build apk завершился ошибкой ($FLUTTER_RC). Пробуем собрать gradle-ом с подробными логами..."
            pushd android >/dev/null

            ./gradlew -v || true

            set +e
            ./gradlew :app:assembleRelease --info --stacktrace
            GRADLE_RC=$?
            set -e

            echo "📁 build outputs под android/app/build/outputs:"
            ls -R app/build/outputs || true

            echo "📁 build outputs под ../build/app/outputs:"
            ls -R ../build/app/outputs || true

            echo "📄 Gradle reports (если существуют):"
            find . -type f -path "*/reports/*" -maxdepth 5 -print || true
            find . -type f -path "*/outputs/*" -maxdepth 5 -name "*.log" -print -exec tail -n +1 {} \; || true

            popd >/dev/null

            if [ $GRADLE_RC -ne 0 ]; then
              echo "❌ Gradle тоже упал (код $GRADLE_RC). См. логи выше."
              exit $GRADLE_RC
            fi
          fi

          echo "✅ Сборка завершена (или успешно по фолбэку)."

      - name: 🔹 Поиск и копирование APK
        script: |
          set -euo pipefail
          echo "🔍 Ищем собранные APK..."
          ls -R build/app/outputs || true

          mkdir -p build/publish

          FOUND_LIST_FILE="$(mktemp)"
          # Стандартные каталоги Flutter/AGP
          ( find build/app/outputs/flutter-apk -type f -name "*release*.apk" -print 2>/dev/null || true ) >> "$FOUND_LIST_FILE"
          ( find build/app/outputs/apk        -type f -name "*release*.apk" -print 2>/dev/null || true ) >> "$FOUND_LIST_FILE"
          # Про запас: нетипичные пути
          ( find build -maxdepth 3 -type f -path "*/outputs/*" -name "*release*.apk" -print 2>/dev/null || true ) >> "$FOUND_LIST_FILE"

          # Удалим дубликаты и пустые строки
          sort -u "$FOUND_LIST_FILE" | sed '/^\s*$/d' > "${FOUND_LIST_FILE}.uniq"

          if [ ! -s "${FOUND_LIST_FILE}.uniq" ]; then
            echo "❌ Не найдено ни одного release APK в стандартных путях."
            echo "Отладка: содержимое build/app/outputs:"
            ls -R build/app/outputs || true
            exit 1
          fi

          echo "✅ Найдены APK:"
          cat "${FOUND_LIST_FILE}.uniq"

          echo "📦 Копируем APK в build/publish ..."
          while IFS= read -r apk; do
            cp -v "$apk" build/publish/
          done < "${FOUND_LIST_FILE}.uniq"

          echo "🎉 Готово. В build/publish лежат:"
          ls -l build/publish

    artifacts:
      - build/publish/*.apk
      - build/app/outputs/flutter-apk/*.apk
      - build/app/outputs/apk/**/*.apk
      - build/**/outputs/**/*.apk

    triggering:
      events:
        - push
      branch_patterns:
        - pattern: "*"
          include: true
          source: true
