workflows:
  android_release:
    name: Android Release APK
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest

    scripts:
      - name: 🔹 Подготовка проекта
        script: |
          set -euo pipefail
          echo "🧹 Очистка и установка зависимостей..."
          flutter clean
          flutter pub get

      - name: 🔹 Сборка релизного APK
        script: |
          set -euo pipefail
          echo "🏗️ Собираем релиз..."
          BN=$(date +%s)
          # Собираем универсальный APK (можно заменить на --split-per-abi)
          flutter build apk --release \
            --build-number="$BN" \
            --build-name="1.0.$BN" \
            --no-shrink

      - name: 🔹 Поиск и копирование APK
        script: |
          set -euo pipefail
          echo "🔍 Ищем собранные APK..."
          ls -R build/app/outputs || true

          mkdir -p build/publish

          # Ищем по всем актуальным путям Flutter/AGP:
          # - build/app/outputs/flutter-apk (современные Flutter)
          # - build/app/outputs/apk        (старые плагины/шаблоны)
          mapfile -t APKS < <( \
            find build/app/outputs/flutter-apk -type f -name "*release*.apk" -print 2>/dev/null; \
            find build/app/outputs/apk        -type f -name "*release*.apk" -print 2>/dev/null \
          )

          if [ "${#APKS[@]}" -eq 0 ]; then
            echo "❌ Не найдено ни одного release APK в стандартных путях."
            exit 1
          fi

          echo "✅ Найдены APK:"
          for f in "${APKS[@]}"; do
            echo "   - $f"
          done

          echo "📦 Копируем APK в build/publish ..."
          for f in "${APKS[@]}"; do
            cp -v "$f" build/publish/
          done

          echo "🎉 Готово. В build/publish лежат:"
          ls -l build/publish

    artifacts:
      # Основной путь, куда мы всё сложили
      - build/publish/*.apk
      # На всякий случай оставим прямые пути (если шаг копирования будет пропущен)
      - build/app/outputs/flutter-apk/*.apk
      - build/app/outputs/apk/**/*.apk

    triggering:
      events:
        - push
      branch_patterns:
        - pattern: "*"
          include: true
          source: true
