workflows:
  android_release:
    name: Android Release APK
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest

    scripts:
      - name: 🔹 Подготовка проекта
        script: |
          set -e
          echo "🧹 Очистка и установка зависимостей..."
          flutter clean
          flutter pub get

      - name: 🔹 Сборка релизного APK
        script: |
          set -e
          echo "🏗️ Собираем именно APK, а не AAB..."
          BN=$(date +%s)
          flutter build apk --release \
            --no-tree-shake-icons \
            --build-number="$BN" \
            --build-name="1.0.$BN" \
            --target-platform android-arm,android-arm64,android-x64
          echo "✅ Проверим, где появился APK:"
          find build -type f -name "*.apk"

      - name: 🔹 Поиск и копирование APK
        script: |
          set -e
          echo "🔍 Ищем собранные APK..."
          ls -R build || true

          mkdir -p build/publish

          APK_PATH=$(find build -type f -name "*release*.apk" -print -quit)

          if [ -z "$APK_PATH" ]; then
            echo "❌ Не найдено ни одного APK-файла. Проверим build/app/outputs:"
            ls -R build/app/outputs || true
            echo "⚠️ Попробуем собрать вручную через Gradle..."
            cd android
            ./gradlew assembleRelease --stacktrace || true
            cd ..
            APK_PATH=$(find build -type f -name "*release*.apk" -print -quit)
          fi

          if [ -z "$APK_PATH" ]; then
            echo "🚨 Ошибка: APK не найден после всех попыток."
            exit 1
          fi

          echo "✅ Найден APK: $APK_PATH"
          cp -v "$APK_PATH" build/publish/

          echo "🎉 Файл успешно скопирован в build/publish"

    artifacts:
      - build/publish/*.apk
      - build/app/outputs/**/*.apk
      - build/**/outputs/**/*.apk

    triggering:
      events:
        - push
      branch_patterns:
        - pattern: "*"
          include: true
          source: true
          
