workflows:
  debug_apk:
    name: Debug APK (fetch notes from GitHub)
    max_build_duration: 60
    environment:
      flutter: stable
      vars:
        APP_NAME: notice_app
        PACKAGE_NAME: com.example.notice_app
    scripts:
      - name: Create Flutter project
        script: |
          set -e
          SAFE_NAME="${APP_NAME// /_}"
          SAFE_NAME="$(echo "$SAFE_NAME" | tr '[:upper:]' '[:lower:]')"
          SAFE_NAME="$(echo "$SAFE_NAME" | sed 's/[^a-z0-9_]/_/g')"
          [[ "$SAFE_NAME" =~ ^[0-9] ]] && SAFE_NAME="app_$SAFE_NAME"
          echo "Using project name: $SAFE_NAME"
          flutter create --org "${PACKAGE_NAME}" --project-name "$SAFE_NAME" --overwrite .

      - name: Fetch Notes main.dart from GitHub raw
        script: |
          set -e
          mkdir -p lib
          RAW_URL="https://raw.githubusercontent.com/v78582514-blip/notes_app_clean/main/main_template.dart"
          echo "Downloading: $RAW_URL"
          # -f: fail on HTTP errors, -L: follow redirects, --retry to be resilient
          curl -fL --retry 3 --retry-delay 2 "$RAW_URL" -o lib/main.dart

          echo "== HEAD of lib/main.dart =="
          sed -n '1,60p' lib/main.dart

          # Валидация: точно не шаблон-счётчик
          if grep -qi "class NotesApp" lib/main.dart && grep -qi "class NotesHomePage" lib/main.dart; then
            echo "✅ Notes code detected."
          else
            echo "❌ Notes markers not found (class NotesApp/NotesHomePage)."
            exit 1
          fi
          if grep -qiE "Counter|MyHomePage" lib/main.dart; then
            echo "❌ Counter template strings found. Aborting."
            exit 1
          fi

      - name: Install dependencies
        script: |
          set -e
          flutter pub add shared_preferences || true
          flutter pub get

      - name: Build release APK (force new version)
        script: |
          set -e
          BN=$(date +%s)
          flutter clean
          flutter build apk --release --build-number="$BN" --build-name="1.0.$BN"

    artifacts:
      - build/app/outputs/flutter-apk/**/*.apk
