workflows:
  android_release:
    name: Android Release APK
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest

    scripts:
      - name: 🔹 Подготовка проекта
        script: |
          set -euo pipefail
          echo "🧹 Очистка и установка зависимостей..."
          flutter clean
          flutter pub get

      - name: 🔹 Сборка релизного APK
        script: |
          set -euo pipefail
          echo "🏗️ Собираем релиз..."
          BN=$(date +%s)
          # Универсальный APK (если нужны отдельные ABIs — см. комментарий ниже)
          flutter build apk --release \
            --build-number="$BN" \
            --build-name="1.0.$BN" \
            --no-shrink
          echo "✅ Сборка завершена."

      - name: 🔹 Поиск и копирование APK
        script: |
          set -euo pipefail
          echo "🔍 Ищем собранные APK..."
          ls -R build/app/outputs || true

          mkdir -p build/publish

          FOUND_LIST_FILE="$(mktemp)"
          # Ищем во всех стандартных каталогах Flutter/AGP
          ( find build/app/outputs/flutter-apk -type f -name "*release*.apk" -print 2>/dev/null || true ) >> "$FOUND_LIST_FILE"
          ( find build/app/outputs/apk        -type f -name "*release*.apk" -print 2>/dev/null || true ) >> "$FOUND_LIST_FILE"
          # Дополнительно просканируем build/**/outputs на случай нетипичных путей
          ( find build -maxdepth 3 -type f -path "*/outputs/*" -name "*release*.apk" -print 2>/dev/null || true ) >> "$FOUND_LIST_FILE"

          # Удалим дубликаты и пустые строки
          sort -u "$FOUND_LIST_FILE" | sed '/^\s*$/d' > "${FOUND_LIST_FILE}.uniq"

          if [ ! -s "${FOUND_LIST_FILE}.uniq" ]; then
            echo "❌ Не найдено ни одного release APK в стандартных путях."
            echo "Отладка: содержимое build/app/outputs:"
            ls -R build/app/outputs || true
            exit 1
          fi

          echo "✅ Найдены APK:"
          cat "${FOUND_LIST_FILE}.uniq"

          echo "📦 Копируем APK в build/publish ..."
          while IFS= read -r apk; do
            cp -v "$apk" build/publish/
          done < "${FOUND_LIST_FILE}.uniq"

          echo "🎉 Готово. В build/publish лежат:"
          ls -l build/publish

    artifacts:
      # Основной каталог, куда мы сложили артефакты
      - build/publish/*.apk
      # На всякий случай — прямые пути, если выше пропустят копирование
      - build/app/outputs/flutter-apk/*.apk
      - build/app/outputs/apk/**/*.apk
      - build/**/outputs/**/*.apk

    triggering:
      events:
        - push
      branch_patterns:
        - pattern: "*"
          include: true
          source: true
          
