workflows:
  android_release:
    name: Android Release APK
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest

    scripts:
      - name: 🔹 Подготовка проекта
        script: |
          set -euo pipefail
          echo "🧹 Очистка и установка зависимостей..."
          flutter clean
          flutter pub get

      - name: 🔹 Сборка релизного APK (напрямую через Gradle)
        script: |
          set -euo pipefail
          echo "🏗️ Собираем release через Gradle (без flutter build apk)…"
          BN=$(date +%s)
          # Обновим версию для Android (Gradle использует ее из local.properties? — нет.
          # Поэтому Flutter-номер версии не обязателен. Главное — собрать assembleRelease)
          pushd android >/dev/null

          # Печатаем версии Gradle/Java для диагностики
          ./gradlew -v || true

          # Сборка релиза
          ./gradlew :app:assembleRelease --info --stacktrace

          echo "📁 Дерево app/build/outputs:"
          ls -R app/build/outputs || true

          popd >/dev/null

      - name: 🔹 Поиск и копирование APK
        script: |
          set -euo pipefail
          echo "🔍 Ищем собранные APK..."

          mkdir -p build/publish

          # Ищем во всех типичных местах:
          # - Gradle outputs (android/app/build/outputs/apk/**)
          # - Flutter outputs (build/app/outputs/**) — на всякий случай
          FOUND_LIST_FILE="$(mktemp)"
          ( find android/app/build/outputs/apk -type f -name "*release*.apk" -print 2>/dev/null || true ) >> "$FOUND_LIST_FILE"
          ( find build/app/outputs            -type f -name "*release*.apk" -print 2>/dev/null || true ) >> "$FOUND_LIST_FILE"
          ( find build                        -maxdepth 4 -type f -name "*release*.apk" -print 2>/dev/null || true ) >> "$FOUND_LIST_FILE"

          sort -u "$FOUND_LIST_FILE" | sed '/^\s*$/d' > "${FOUND_LIST_FILE}.uniq"

          if [ ! -s "${FOUND_LIST_FILE}.uniq" ]; then
            echo "❌ Не найдено ни одного release APK."
            echo "🔎 Отладка: android/app/build/outputs содержимое:"
            ls -R android/app/build/outputs || true
            echo "🔎 Отладка: build/app/outputs содержимое:"
            ls -R build/app/outputs || true
            exit 1
          fi

          echo "✅ Найдены APK:"
          cat "${FOUND_LIST_FILE}.uniq"

          echo "📦 Копируем APK в build/publish ..."
          while IFS= read -r apk; do
            cp -v "$apk" build/publish/
          done < "${FOUND_LIST_FILE}.uniq"

          echo "🎉 Готово. В build/publish лежат:"
          ls -l build/publish

    artifacts:
      - build/publish/*.apk
      - android/app/build/outputs/apk/**/*.apk
      - build/app/outputs/**/*.apk
      - build/**/outputs/**/*.apk

    triggering:
      events:
        - push
      branch_patterns:
        - pattern: "*"
          include: true
          source: true
          
