workflows:
  debug_apk:
    name: Debug APK (safe)
    max_build_duration: 60
    environment:
      flutter: stable
      vars:
        APP_NAME: notice_app
        PACKAGE_NAME: com.example.notice_app
    scripts:
      - name: Create Flutter project
        script: |
          SAFE_NAME="${APP_NAME// /_}"
          SAFE_NAME="$(echo "$SAFE_NAME" | tr '[:upper:]' '[:lower:]')"
          SAFE_NAME="$(echo "$SAFE_NAME" | sed 's/[^a-z0-9_]/_/g')"
          if [[ "$SAFE_NAME" =~ ^[0-9] ]]; then SAFE_NAME="app_$SAFE_NAME"; fi
          flutter create --org "${PACKAGE_NAME}" --project-name "$SAFE_NAME" --overwrite .

      - name: Copy main.dart
        script: |
          mkdir -p lib
          cp -f "$CM_SOURCE_DIR/main_template.dart" lib/main.dart
          echo "== HEAD of lib/main.dart =="
          head -n 20 lib/main.dart

      - name: Install dependencies
        script: |
          flutter pub add shared_preferences || true
          flutter pub get

      - name: Build release APK
        script: flutter build apk --release

    artifacts:
      - build/app/outputs/flutter-apk/**/*.apk
