name: notice_app
publish_to: "none"
description: Simple notes app with groups, sharing, export/import, private groups
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.3
  share_plus: ^10.0.2
  flutter_secure_storage: ^9.2.2

flutter:
  uses-material-design: true
