name: notice_app
description: Notes app with groups and private mode
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.3
  crypto: ^3.0.3

flutter:
  uses-material-design: true
